In [361]:
import numpy as np
import scipy.stats as st

In [362]:
y=np.matrix([[110], [140], [180], [190]])
X=np.matrix([[180,150], [150,175], [170,165], [185,210]])

In [363]:
N = y.shape[0]
X_m=np.mean(X,axis=0)

In [364]:
# Calc Theta
Theta = np.linalg.inv(np.dot(X.T, X))
Theta = np.dot(Theta, X.T)
Theta = np.dot(Theta, y)

In [365]:
# Calc Sigma
sigma = 0
for i in range(N):
    ans = (y[i]-np.dot(X[i], Theta))[0,0]
    sigma = sigma + ans * ans
sigma = sigma / (N)
Sigma = np.diag([sigma]*N)

In [366]:
print("Sigma=\n", Sigma)
print("Theta=\n", Theta)

Sigma=
 [[470.7155107   0.          0.          0.       ]
 [  0.        470.7155107   0.          0.       ]
 [  0.          0.        470.7155107   0.       ]
 [  0.          0.          0.        470.7155107]]
Theta=
 [[-0.11278259]
 [ 0.99759605]]


In [367]:
x=np.matrix([[175], [170]])
y_hat = np.dot(x.T, Theta)
print("y_hat=\n", y_hat)

y_hat=
 [[149.85437495]]


In [368]:
np.dot(np.dot(x.T, np.linalg.inv(np.dot(np.dot(X.T, np.linalg.inv(Sigma)), X))),x)[0,0] * sigma


64382.72609959852

In [371]:
st.norm.interval(0.95, loc=y_hat, scale=1)

(array([[147.89441096]]), array([[151.81433893]]))